kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-clusterrolebinding-flexvolume
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: default
  apiGroup:
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-clusterrole-flexvolume
  apiGroup: rbac.authorization.k8s.io