apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
  name: "system:serviceaccount:{{ .Release.Namespace }}:default"
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
  name: "system:serviceaccount:{{ .Release.Namespace }}:default"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "system:serviceaccount:{{ .Release.Namespace }}:default"
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
