kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nlz-utils-clusterrolebinding-flexvolume
subjects:
- kind: ServiceAccount
  namespace: kube-system
  name: default
  apiGroup:
roleRef:
  kind: ClusterRole
  name: clusterrole-flexvolume
  apiGroup: rbac.authorization.k8s.io