apiVersion: apps/v1
kind: DaemonSet
metadata:
#  namespace: nlz-utils
  name: nlz-utils-datasets
spec:
  selector:
    matchLabels:
      name: nlz-utils-datasets
  template:
    metadata:
      labels:
        name: nlz-utils-datasets
      name: nlz-utils-datasets
    spec:
      containers:
        - image: nerdalize/nerd-flex-volume:dev0106
          name: nlz-utils-datasets
          imagePullPolicy: Always
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /flexmnt
              name: flexvolume-mount
      volumes:
        - name: flexvolume-mount
          hostPath:
            path: /var/lib/kubelet/volumeplugins/
