kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nlz-utils-clusterrole-flexvolume
rules:
- apiGroups:
  - stable.nerdalize.com
  resources:
  - datasets
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - resourcequotas
  - resourcequotas/status
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get

