apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:serviceaccount:default:default
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - stable.nerdalize.com
  resources:
  - datasets
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - ""
  resources:
  - resourcequotas
  - resourcequotas/status
  - namespaces
  verbs:
  - get
  - list
 
